#!/usr/bin/env bash
#
# ai/jaAgents/bootstrap.sh —— Multica worktree 开工第一步。
#
# 放在 ai/jaAgents/ 而不是 scripts/：它和 MULTICA.md 是一对，整个 ai/ 目录搬到别的项目照样能用。
#
# Multica 给每个 issue 新开一个 git worktree，里面只有 tracked 文件：
# `.claude/` / `.agents/` 与根目录 `CLAUDE.md` / `AGENTS.md` 全都 gitignored，所以一开始都不存在，
# agent 一个技能也看不见、一份协议也读不到。本脚本把两样东西就地生出来：
#
#   1. 技能：把 ai/jaSkills/ 下的全部技能复制进 agent 自己的技能目录
#        Claude 系 → .claude/skills/<name>/
#        Codex  系 → .agents/skills/<name>/
#   2. 协议：把 ai/jaAgents/MULTICA.md 复制成根目录的 CLAUDE.md（Claude 系）或 AGENTS.md（Codex 系）
#
# 落点全部 gitignored，不会混进提交。真源仍只有 ai/jaSkills/ 与 ai/jaAgents/MULTICA.md 两处，要改就改真源。
#
# 用法：
#   bash ai/jaAgents/bootstrap.sh                 # 按环境变量自动判断是 claude 还是 codex；判断不了就两边都建
#   bash ai/jaAgents/bootstrap.sh --agent claude  # 只建 Claude 侧
#   bash ai/jaAgents/bootstrap.sh --agent codex   # 只建 Codex 侧
#   bash ai/jaAgents/bootstrap.sh --agent all     # 两边都建
#   bash ai/jaAgents/bootstrap.sh --force         # 连没有生成标记的根目录 CLAUDE.md / AGENTS.md 也覆盖（本机慎用）
#
# 本机开发者的保护：
#   - 技能目录里已经是指向 ai/jaSkills/ 的 symlink（scripts/skills-link.sh 建的）→ 原样保留，不换成副本
#   - 根目录 CLAUDE.md / AGENTS.md 存在且没有本脚本的生成标记 → 视为个人协议，不覆盖（除非 --force）
#
# 重复执行安全。
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"   # ai/jaAgents/ → 仓库根
cd "$ROOT"

SRC_SKILLS="ai/jaSkills"
SRC_PROTOCOL="ai/jaAgents/MULTICA.md"
MARKER="<!-- generated by ai/jaAgents/bootstrap.sh from ai/jaAgents/MULTICA.md — 不要手改，要改就改真源 -->"

AGENT="auto"
FORCE=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --agent) AGENT="${2:-}"; shift 2 ;;
    --agent=*) AGENT="${1#*=}"; shift ;;
    --force) FORCE=1; shift ;;
    -h|--help) sed -n '2,32p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "✗ 未知参数：$1（用 --help 看用法）"; exit 2 ;;
  esac
done

[[ -d "$SRC_SKILLS" ]]   || { echo "✗ 找不到 $SRC_SKILLS —— 技能真源不在，先确认分支是否已合入"; exit 1; }
[[ -f "$SRC_PROTOCOL" ]] || { echo "✗ 找不到 $SRC_PROTOCOL —— 协议真源不在，先确认分支是否已合入"; exit 1; }

if [[ "$AGENT" == "auto" ]]; then
  if [[ -n "${CLAUDECODE:-}" || -n "${CLAUDE_CODE_ENTRYPOINT:-}" ]]; then
    AGENT="claude"
  elif [[ -n "${CODEX_SANDBOX:-}" || -n "${CODEX_HOME:-}" || -n "${CODEX_THREAD_ID:-}" || -n "${CODEX_CI:-}" ]]; then
    AGENT="codex"
  else
    AGENT="all"
  fi
fi

case "$AGENT" in
  claude) SIDES=("claude") ;;
  codex)  SIDES=("codex") ;;
  all)    SIDES=("claude" "codex") ;;
  *) echo "✗ --agent 只接受 claude / codex / all，收到：$AGENT"; exit 2 ;;
esac

copied=0; kept=0; protocols=0; skipped=0

copy_tree() {
  # $1 = 源目录（带尾斜杠） $2 = 目标目录
  if command -v rsync >/dev/null 2>&1; then
    rsync -a --delete --exclude='.DS_Store' "$1" "$2/"
  else
    rm -rf "$2"; mkdir -p "$2"; cp -R "$1". "$2/"
  fi
}

fill_skills() {
  local dir="$1"
  mkdir -p "$dir"
  for src in "$SRC_SKILLS"/*/; do
    local name; name="$(basename "$src")"
    local dest="$dir/$name"
    local rel="../../$SRC_SKILLS/$name"
    if [[ -L "$dest" ]]; then
      if [[ "$(readlink "$dest")" == "$rel" ]]; then kept=$((kept + 1)); continue; fi
      rm "$dest"   # 指错地方的旧链接：删 symlink 不碰内容
    fi
    copy_tree "$src" "$dest"
    copied=$((copied + 1))
  done
  # 真源里已没有、目录里还剩的副本：只报告不删——可能是别人正在加的东西
  for leftover in "$dir"/*/; do
    [[ -d "$leftover" ]] || continue
    local n; n="$(basename "$leftover")"
    [[ -d "$SRC_SKILLS/$n" ]] || echo "⚠ $leftover 在真源 $SRC_SKILLS/ 里不存在，已保留未动"
  done
}

write_protocol() {
  local file="$1"
  if [[ -e "$file" && $FORCE -eq 0 ]]; then
    if ! head -n 1 "$file" | grep -qF "generated by ai/jaAgents/bootstrap.sh"; then
      echo "⚠ $file 已存在且不是本脚本生成的（多半是本机个人协议），未覆盖。Multica worktree 里若确需覆盖，加 --force"
      skipped=$((skipped + 1)); return
    fi
  fi
  { echo "$MARKER"; echo; cat "$SRC_PROTOCOL"; } > "$file"
  protocols=$((protocols + 1))
}

for side in "${SIDES[@]}"; do
  case "$side" in
    claude) fill_skills ".claude/skills"; write_protocol "CLAUDE.md" ;;
    codex)  fill_skills ".agents/skills"; write_protocol "AGENTS.md" ;;
  esac
done

echo "✓ agent=$AGENT · 复制技能 $copied 个$( ((kept)) && echo " · 保留 symlink $kept 条" ) · 生成协议 $protocols 份$( ((skipped)) && echo " · 跳过 $skipped 份（已有个人协议）" )"
for side in "${SIDES[@]}"; do
  case "$side" in
    claude) echo "→ 下一步：从头读一遍 ./CLAUDE.md，按其 §一 准备上下文，然后再开始干活" ;;
    codex)  echo "→ 下一步：从头读一遍 ./AGENTS.md，按其 §一 准备上下文，然后再开始干活" ;;
  esac
done
